#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# The half of issue #29 that needs credentials: the Neon project, the
# Vercel–Neon integration, the first migration, and a preview deploy with a
# working admin panel. Follows ADR-0001 (hosting) and ADR-0005 (migrations).
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
ENV_FILE=".env.local"

# Every prompt here is a `read`. Without an interactive stdin they all return
# EOF immediately, and the wizard runs start to finish answering nothing —
# writing an empty DATABASE_URL and a throwaway PAYLOAD_SECRET on its way past.
# That happened once. Refuse instead.
if [[ ! -t 0 ]]; then
  printf '\n%s  This wizard needs an interactive terminal.%s\n\n' "$RED" "$RESET"
  printf '  stdin is not a TTY, so every prompt would read EOF and be skipped.\n'
  printf '  Run it directly in your own terminal:\n\n'
  printf '      %sbash scripts/setup-infrastructure.sh%s\n\n' "$BOLD" "$RESET"
  printf '  Not through a pipe, and not from inside an agent or CI session.\n\n'
  exit 1
fi

banner "ThuisBakery infrastructure (issue #29)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Vercel CLI and login"
say "Hobby is fine for building. ADR-0001's Pro requirement is about commercial"
say "use, which starts at launch, not now — so the upgrade is a launch-blocker"
say "on docs/launch-checklist.md rather than a step here."
note "Checked against Vercel's docs: Hobby allows a single Function region, and"
note "vercel.json pins exactly one (fra1). Nothing in issue #29 needs Pro."
step "Install the CLI if you haven't: pnpm add -g vercel"
step "Log in: vercel login"
note "The team to deploy under is 'dparfitt's projects'."
pause "Logged in?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create the Vercel project"
say "Import the GitHub repo so pushes deploy themselves."
open_url "https://vercel.com/new"
step "Import ThuisBakeryTech/ThuisBakery."
step "Framework preset: Next.js. Leave Build Command on the default."
warn "Do NOT deploy yet, and do NOT add any environment variables here."
note "The default build runs package.json's 'build' script, which is"
note "'payload migrate && next build' (ADR-0005). Stage 8 verifies that."
step "If it deploys and fails for want of a database, that is expected."
ask VERCEL_PROJECT_NAME "Project name as Vercel created it:"
say "Linking this checkout to it:"
step "Run: vercel link"
pause "Project created and linked?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Provision Neon: Frankfurt, Free"
say "Provisioning through Vercel's native Neon integration is what makes"
say "DATABASE_URL an injected, per-deployment value rather than a pasted one."
step "Run: vercel integration add neon"
step "When prompted, choose:"
note "  Plan     · Free  (ADR-0001; upgrade to Launch at the first real migration)"
note "  Region   · Europe (Frankfurt) / eu-central-1, next to the fra1 functions"
note "  Connect  · this project, for Production AND Preview AND Development"
say "If the CLI does not offer a region, set it in the Neon dashboard before"
say "creating any data — the region cannot be changed afterwards."
ask NEON_PROJECT_NAME "Neon resource name as you named it:"
pause "Neon provisioned and connected?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Confirm per-preview branching and hands-off DATABASE_URL"
say "Two things to verify, both load-bearing for ADR-0005's 'the preview"
say "deployment is the rehearsal'."
open_url "https://vercel.com/dashboard/stores"
step "Open the Neon resource, then its Neon dashboard (vercel integration open neon)."
step "Confirm preview/branch-per-deployment is enabled for this project."
note "Neon Free allows 10 branches. Production + a long-lived 'dev' leaves eight."
open_url "https://vercel.com/dashboard"
step "Project → Settings → Environment Variables."
step "Confirm DATABASE_URL and DATABASE_URL_UNPOOLED appear as integration-owned."
warn "Never add either by hand here. A hand-set value shadows the per-branch one."
pause "Branching on, and no hand-set DATABASE_URL?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "PAYLOAD_SECRET"
say "Payload's signing secret. Unlike DATABASE_URL, this one is ours to set."
PAYLOAD_SECRET_VALUE="$(_existing PAYLOAD_SECRET || true)"
if [[ -n "$PAYLOAD_SECRET_VALUE" ]]; then
  say "Reusing the secret already in $ENV_FILE."
  note "Re-running this wizard must not mint a new one: that would invalidate"
  note "every existing login session, including Jana's."
else
  PAYLOAD_SECRET_VALUE="$(openssl rand -hex 32)"
  say "Generated a fresh 32-byte secret."
fi
write_env PAYLOAD_SECRET "$PAYLOAD_SECRET_VALUE"
step "Add the same value to Vercel, for all three environments:"
note "  vercel env add PAYLOAD_SECRET production"
note "  vercel env add PAYLOAD_SECRET preview"
note "  vercel env add PAYLOAD_SECRET development"
say "The value, to paste (it is already in $ENV_FILE):"
printf '  %s%s%s\n' "$BOLD" "$PAYLOAD_SECRET_VALUE" "$RESET"
warn "Changing this later invalidates every existing login session."
pause "Set in all three Vercel environments?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "The long-lived Neon 'dev' branch"
say "ADR-0001: no database ever runs locally. Local points at one persistent"
say "Neon branch instead. This is the only connection string pasted by hand."
step "Run: vercel integration open neon"
step "In Neon: Branches → New branch, named 'dev', branched from production."
step "On the dev branch's Connect panel, copy BOTH strings:"
note "  the pooled one   (host contains '-pooler')  → DATABASE_URL"
note "  the direct one   (no '-pooler')             → DATABASE_URL_UNPOOLED"
ask_secret DATABASE_URL "Paste the POOLED connection string:"
ask_secret DATABASE_URL_UNPOOLED "Paste the UNPOOLED connection string:"
write_env DATABASE_URL "$DATABASE_URL"
write_env DATABASE_URL_UNPOOLED "$DATABASE_URL_UNPOOLED"
note "$ENV_FILE is gitignored. These never go into Vercel by hand."
pause "Both strings saved?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "The first migration"
say "Payload's Users collection needs a migration before any deploy can run"
say "'payload migrate'. Generated locally, read, then committed (ADR-0005)."
warn "Commit this on a BRANCH, not on main. A commit to main deploys to"
warn "Production, so the migration would meet the production database with no"
warn "rehearsal — the exact thing ADR-0005 built the preview branch to avoid."
step "Run: git switch -c first-migration"
step "Run: pnpm run migrate:create"
step "Read the generated file in src/migrations/ before committing it."
warn "Any DROP is a stop-and-think, never a rubber stamp. On a first migration"
warn "there should be none — only CREATE TABLE."
step "Then: git add src/migrations && git commit"
if confirm "Have you read the migration and seen no unexpected DROP?"; then
  say "Good."
else
  SKIPPED+=("read src/migrations/*.ts for DROP statements before committing")
  warn "Recorded as outstanding. Do not deploy until you have read it."
fi
pause "Migration generated and committed?"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Preview deploy and the admin panel"
say "The last acceptance criterion: the admin panel loads on a deployed"
say "preview URL. This is also ADR-0001's cold-start measurement."
step "Run: git push -u origin first-migration"
step "Open a pull request against main. The PR gets a Vercel preview, and the"
note "Neon integration gives that preview its own branch of the database."
step "Wait for the preview to build."
step "In the build log, confirm the first line of the build is 'payload migrate'"
note "and that it reports the migration applied. That is the rehearsal working."
step "Open <preview-url>/admin and create the first admin user."
ask PREVIEW_URL "Paste the preview URL (nothing is written to $ENV_FILE):"
say "Opening the admin panel:"
open_url "${PREVIEW_URL%/}/admin"
warn "Time the first load. ADR-0001 accepted roughly seven seconds of cold"
warn "start as the price of Vercel. If it is bad enough that Jana would notice,"
warn "the 'reconsider Render or Fly' trigger has fired — say so on issue #29."
if confirm "Did the admin panel load and accept a first user?"; then
  say "That is issue #29 complete."
else
  SKIPPED+=("admin panel on a preview URL — the last AC of issue #29")
fi

finish
