/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    items: Item;
    categories: Category;
    occasions: Occasion;
    sponges: Sponge;
    fillings: Filling;
    allergens: Allergen;
    media: Media;
    submissions: Submission;
    users: User;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    items: ItemsSelect<false> | ItemsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    occasions: OccasionsSelect<false> | OccasionsSelect<true>;
    sponges: SpongesSelect<false> | SpongesSelect<true>;
    fillings: FillingsSelect<false> | FillingsSelect<true>;
    allergens: AllergensSelect<false> | AllergensSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'nl') | ('en' | 'nl')[];
  globals: {
    header: Header;
    footer: Footer;
    home: Home;
    'cross-contamination': CrossContamination;
    'lead-time': LeadTime;
    'closed-until': ClosedUntil;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    'cross-contamination': CrossContaminationSelect<false> | CrossContaminationSelect<true>;
    'lead-time': LeadTimeSelect<false> | LeadTimeSelect<true>;
    'closed-until': ClosedUntilSelect<false> | ClosedUntilSelect<true>;
  };
  locale: 'en' | 'nl';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items".
 */
export interface Item {
  id: number;
  title: string;
  /**
   * The last part of this Item’s URL, in this locale’s own words — apple-pie, appeltaart.
   */
  slug: string;
  /**
   * Exactly one. The Category also decides which catalogue page this Item lives under.
   */
  category: number | Category;
  /**
   * Optional. Used to build landing pages — never to organise the menu.
   */
  occasions?: (number | Occasion)[] | null;
  /**
   * The first photograph is the one the catalogue page shows.
   */
  photographs?: (number | Media)[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * On: the customer chooses a Sponge and a Filling from the shared lists. Off: this Item is sold exactly as described.
   */
  configurable?: boolean | null;
  /**
   * Which of the shared Sponges a customer may choose for this Item. Leave empty to offer every Sponge.
   */
  sponges?: (number | Sponge)[] | null;
  /**
   * Which of the shared Fillings a customer may choose. Leave empty to offer every Filling. A Filling’s Surcharge is set on the Filling, never here.
   */
  fillings?: (number | Filling)[] | null;
  /**
   * A priced variant of this Item. An Item that comes only one way has exactly one Size.
   */
  sizes: {
    /**
     * What a customer calls this Size — Small, 6 inch, Bento.
     */
    label: string;
    /**
     * Centimetres. Leave empty for an Item that is not round.
     */
    diameter?: number | null;
    /**
     * Layer count.
     */
    layers?: number | null;
    /**
     * Serving count.
     */
    servings?: number | null;
    /**
     * Euros. Shown on the page — the Estimate and the page must agree.
     */
    price: number;
    id?: string | null;
  }[];
  /**
   * What this Item contains. The cross-contamination statement is site-wide and is never written here.
   */
  allergens?: (number | Allergen)[] | null;
  /**
   * Only for an Item that needs more notice than the site-wide Lead time. Days and time of day are a pair — set both, or clear both.
   */
  leadTime?: {
    /**
     * Whole days of notice an Enquiry must give.
     */
    days?: number | null;
    /**
     * The time by which an Enquiry must arrive to count as arriving that day. The other half of the Lead time — an Enquiry sent after it has missed the day it was sent on.
     */
    timeOfDay?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Jana’s own name for this Category — Proefhapjes, Cheeky Bento Cakes, Indulgent Cakes, Specialty Cakes, Nibbles.
   */
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * Where the catalogue page scrolls to for this Category — /cakes#bento. Changing it breaks links people have shared.
   */
  slug: string;
  /**
   * The line under the name on the card — “Mini Cakes for Big Moments”.
   */
  tagline: string;
  /**
   * Optional. The italic line beneath, where the card has one — “personalisation available on request”.
   */
  note?: string | null;
  /**
   * The photograph this Category is shown as. Set its focal point on the photograph itself, so the cake stays in frame when the menu crops it.
   */
  photograph: number | Media;
  /**
   * Euros, as on the card — 29. Leave empty for a Category priced Item by Item, like Specialty or Nibbles.
   */
  price?: number | null;
  /**
   * Shows “from €25” rather than “€25”.
   */
  priceFrom?: boolean | null;
  /**
   * Which catalogue page this tier appears on. Cakes are Configurable and are bought as a conversation; Nibbles are fixed and are bought as a quantity.
   */
  catalogue: 'cakes' | 'nibbles';
  /**
   * Where this tier sits on the catalogue page. Lowest first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prefix?: string | null;
  _objectKey?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions".
 */
export interface Occasion {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponges".
 */
export interface Sponge {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fillings".
 */
export interface Filling {
  id: number;
  name: string;
  /**
   * Euros this Filling adds to an Item’s price. Leave empty for no Surcharge.
   */
  surcharge?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "allergens".
 */
export interface Allergen {
  id: number;
  name: string;
  icon: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every Enquiry customers have sent, newest first. Use Filters to narrow by type, Item, language or Requested pickup date.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  /**
   * Which form this came from.
   */
  enquiryType: 'item' | 'custom-order' | 'contact';
  /**
   * The language the customer wrote in — the one to reply in.
   */
  locale: 'en' | 'nl';
  name: string;
  email: string;
  phone?: string | null;
  /**
   * The Item page this was sent from.
   */
  item?: (number | null) | Item;
  /**
   * The Item’s title when the customer sent this, in their language.
   */
  itemTitle?: string | null;
  size?: string | null;
  quantity?: number | null;
  sponge?: string | null;
  filling?: string | null;
  /**
   * Requested, never confirmed: only Jana’s reply confirms a date.
   */
  requestedPickupDate?: string | null;
  /**
   * The customer’s own words, never priced by the Estimate.
   */
  specialRequests?: string | null;
  message?: string | null;
  /**
   * Exactly what the customer was shown, stored when they sent it and never recomputed. Provisional: your reply sets the price.
   */
  estimate?: {
    lines?:
      | {
          label: string;
          unitAmount: number;
          quantity: number;
          amount: number;
          id?: string | null;
        }[]
      | null;
    total?: number | null;
    currency?: 'EUR' | null;
    provisional?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'items';
        value: number | Item;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'occasions';
        value: number | Occasion;
      } | null)
    | ({
        relationTo: 'sponges';
        value: number | Sponge;
      } | null)
    | ({
        relationTo: 'fillings';
        value: number | Filling;
      } | null)
    | ({
        relationTo: 'allergens';
        value: number | Allergen;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items_select".
 */
export interface ItemsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  occasions?: T;
  photographs?: T;
  description?: T;
  configurable?: T;
  sponges?: T;
  fillings?: T;
  sizes?:
    | T
    | {
        label?: T;
        diameter?: T;
        layers?: T;
        servings?: T;
        price?: T;
        id?: T;
      };
  allergens?: T;
  leadTime?:
    | T
    | {
        days?: T;
        timeOfDay?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  tagline?: T;
  note?: T;
  photograph?: T;
  price?: T;
  priceFrom?: T;
  catalogue?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions_select".
 */
export interface OccasionsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponges_select".
 */
export interface SpongesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fillings_select".
 */
export interface FillingsSelect<T extends boolean = true> {
  name?: T;
  surcharge?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "allergens_select".
 */
export interface AllergensSelect<T extends boolean = true> {
  name?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  _objectKey?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  enquiryType?: T;
  locale?: T;
  name?: T;
  email?: T;
  phone?: T;
  item?: T;
  itemTitle?: T;
  size?: T;
  quantity?: T;
  sponge?: T;
  filling?: T;
  requestedPickupDate?: T;
  specialRequests?: T;
  message?: T;
  estimate?:
    | T
    | {
        lines?:
          | T
          | {
              label?: T;
              unitAmount?: T;
              quantity?: T;
              amount?: T;
              id?: T;
            };
        total?: T;
        currency?: T;
        provisional?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * The navigation links, in order. Keep it short: four is the design.
   */
  links: {
    page: 'home' | 'cakes' | 'nibbles' | 'customOrder' | 'about' | 'contact' | 'privacy';
    label: string;
    id?: string | null;
  }[];
  /**
   * The one link shown as a button. Custom order, by design.
   */
  callToAction: {
    page: 'home' | 'cakes' | 'nibbles' | 'customOrder' | 'about' | 'contact' | 'privacy';
    label: string;
    id?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * The short line under the name.
   */
  tagline: string;
  /**
   * Every page on the site, in order.
   */
  links: {
    page: 'home' | 'cakes' | 'nibbles' | 'customOrder' | 'about' | 'contact' | 'privacy';
    label: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero: {
    /**
     * The page’s heading — “Baked at home in Uithoorn”.
     */
    headline: string;
    /**
     * One or two sentences under the heading.
     */
    intro: string;
    /**
     * The photograph along the foot of the opening screen, cut by the bottom edge so it leads down into the menu. A wide shot works best. Set its focal point on the photograph itself, so the cake stays in frame when the page crops it.
     */
    photograph?: (number | null) | Media;
    /**
     * The main button, to the cakes — “See the cakes”.
     */
    cakesLabel: string;
    /**
     * The link beside it, to the nibbles.
     */
    nibblesLabel: string;
  };
  /**
   * Three facts under the opening. The notice needed comes from Lead time, and the starting price from the Categories — only pickup and the line under the price are written here.
   */
  facts: {
    /**
     * Where cakes are collected — “Pickup in Uithoorn”.
     */
    pickupTitle: string;
    /**
     * The line beneath — “Address sent once your day is confirmed.”
     */
    pickupDetail: string;
    /**
     * Optional. The line under the starting price — “A bento cake. Full sizes run to about €110.”
     */
    priceDetail?: string | null;
  };
  /**
   * The menu shows every Category, as it does on the catalogue pages.
   */
  menu: {
    /**
     * The heading above the menu — “The menu”.
     */
    heading: string;
  };
  about: {
    /**
     * “One kitchen, one pair of hands”.
     */
    heading: string;
    /**
     * A few sentences. Leave a blank line between paragraphs.
     */
    body: string;
    /**
     * The link to the About page — “Meet Jana”.
     */
    linkLabel: string;
    /**
     * A photograph of Jana, or of her kitchen. Tall rather than wide. Set its focal point on the photograph itself, so the cake stays in frame when the page crops it.
     */
    photograph?: (number | null) | Media;
  };
  /**
   * The cross-contamination statement is added beneath automatically; it is written once, on its own global.
   */
  allergens: {
    /**
     * “About allergies”.
     */
    heading: string;
    /**
     * Optional. A sentence before the statement.
     */
    intro?: string | null;
  };
  quote: {
    /**
     * What the customer said, without quotation marks.
     */
    text: string;
    /**
     * Who said it — “Marieke, Uithoorn”. Ask before using a surname.
     */
    attribution: string;
  };
  faq: {
    /**
     * “Before you ask”.
     */
    heading: string;
    questions: {
      /**
       * The question, as a customer would ask it.
       */
      question: string;
      /**
       * The answer.
       */
      answer: string;
      id?: string | null;
    }[];
  };
  /**
   * The last section, sending the customer into the menu. It uses the Opening’s button and link words.
   */
  closing: {
    /**
     * “Tell Jana what the day is for”.
     */
    heading: string;
    /**
     * One or two sentences.
     */
    body: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cross-contamination".
 */
export interface CrossContamination {
  id: number;
  /**
   * Shown alongside every Allergen list, on every Item.
   */
  statement: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-time".
 */
export interface LeadTime {
  id: number;
  /**
   * Whole days of notice an Enquiry must give.
   */
  days: number;
  /**
   * The time by which an Enquiry must arrive to count as arriving that day. The other half of the Lead time — an Enquiry sent after it has missed the day it was sent on.
   */
  timeOfDay: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "closed-until".
 */
export interface ClosedUntil {
  id: number;
  /**
   * Leave empty when open. While set, a customer cannot ask to collect before this date, and the site says so.
   */
  date?: string | null;
  /**
   * What the site says while closed. Shown only when a date is set.
   */
  notice?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  links?:
    | T
    | {
        page?: T;
        label?: T;
        id?: T;
      };
  callToAction?:
    | T
    | {
        page?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  links?:
    | T
    | {
        page?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        intro?: T;
        photograph?: T;
        cakesLabel?: T;
        nibblesLabel?: T;
      };
  facts?:
    | T
    | {
        pickupTitle?: T;
        pickupDetail?: T;
        priceDetail?: T;
      };
  menu?:
    | T
    | {
        heading?: T;
      };
  about?:
    | T
    | {
        heading?: T;
        body?: T;
        linkLabel?: T;
        photograph?: T;
      };
  allergens?:
    | T
    | {
        heading?: T;
        intro?: T;
      };
  quote?:
    | T
    | {
        text?: T;
        attribution?: T;
      };
  faq?:
    | T
    | {
        heading?: T;
        questions?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  closing?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cross-contamination_select".
 */
export interface CrossContaminationSelect<T extends boolean = true> {
  statement?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-time_select".
 */
export interface LeadTimeSelect<T extends boolean = true> {
  days?: T;
  timeOfDay?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "closed-until_select".
 */
export interface ClosedUntilSelect<T extends boolean = true> {
  date?: T;
  notice?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}